os: 
  - osx

language: generic
osx_image: xcode9.2
script:
  - xcodebuild -showsdks
  - xcodebuild -scheme TABSwiftLayout -configuration Debug -sdk iphonesimulator11.2 -destination "OS=11.2,name=iPhone 6s Plus" test